<a href="https://colab.research.google.com/github/SangeerthanaBalasubramaniam/Machine-Learning/blob/main/LAB5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Label Encoder**


In [ ]:
import numpy as np
from sklearn import preprocessing
encoder= preprocessing.LabelEncoder()

In [ ]:
y=np.array(["Apple", "apple", "apple", "orange","orange"])

In [ ]:
yencode1=encoder.fit(y)
list(yencode1.classes_)

['Apple', 'apple', 'orange']

In [ ]:
yencode=encoder.fit_transform(y)

In [ ]:
print(yencode)


[0 1 1 2 2]


## **Ordinal Encoder**

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male'], ['Female'], ['Female'],['others'],['others']]
print(X)

[['Male'], ['Female'], ['Female'], ['others'], ['others']]


In [ ]:
enc.fit(X)
list(enc.categories_)

[array(['Female', 'Male', 'others'], dtype=object)]

In [ ]:
ord=enc.transform(X)

In [ ]:
print(ord)

[[1.]
 [0.]
 [0.]
 [2.]
 [2.]]


## **Onehot Encoder**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
y=(["Apple"], ["apple"], ["apple"], ["orange"],["orange"])
oneenc=OneHotEncoder()

In [ ]:
oneenc.fit(y)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [ ]:
out=oneenc.transform(y).toarray()

In [ ]:
print(out)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [ ]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
print(data)
print("Mean",np.mean(data))

[[0, 0], [0, 0], [1, 1], [1, 1]]
Mean 0.5


In [ ]:
scaler = StandardScaler()
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [ ]:
 print(scaler.mean_)

[0.5 0.5]


In [ ]:
transformeddata=scaler.transform(data)
print(transformeddata)

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
